### ISSUE TITLE
Crash with latest gem 1.0 of straight-server

### ISSUE THREAD

**Issue by MBuffenoir** [MyceliumGear/straight-server#15]
When I run straight-server I get:

/var/lib/gems/2.1.0/gems/straight-1.0.0/lib/straight/faraday_monkeypatch.rb:1: warning: already initialized constant Faraday::SSLOptions
/var/lib/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/options.rb:205: warning: previous definition of SSLOptions was here
Setting config dir to /usr/src/app/straight-server-config
/var/lib/gems/2.1.0/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:198:in `setup_redis_connection': Redis not configured (RuntimeError)
	from /var/lib/gems/2.1.0/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:44:in `prepare'
	from /var/lib/gems/2.1.0/gems/straight-server-1.0.0/lib/straight-server/server.rb:10:in `initialize'
	from /var/lib/gems/2.1.0/gems/goliath-1.0.4/lib/goliath/application.rb:105:in `new'
	from /var/lib/gems/2.1.0/gems/goliath-1.0.4/lib/goliath/application.rb:105:in `run!'
	from /var/lib/gems/2.1.0/gems/goliath-1.0.4/lib/goliath/application.rb:133:in `block in <module:Goliath>'

My config specifies:

db:
  adapter: postgresql
  host: db
  encoding: unicode
  database: straight
  user: postgres
  password: postgres

**Comment by snitko** [comment]
Redis is now a required dependency. You need to install redis on your system and the redis config lines to your confg file. You can see an example here: https://github.com/MyceliumGear/straight-server/blob/master/templates/config.yml#L36-L40

**Comment by MBuffenoir** [comment]
Thanks updating my docker-compose and config.yml files accordingly.
