### ISSUE TITLE
Crash on ubuntu 15.04

### ISSUE THREAD

**Issue by MBuffenoir** [MyceliumGear/straight-server#2]
Hello,

I have the following error:

 [2015-07-24T14:36:41.262372 #11] FATAL -- : NoMethodError: undefined method `start_periodic_status_check' for #<Hash:0x0000000156fe68>
Backtrace:
    /var/lib/gems/2.1.0/gems/straight-server-0.2.3/lib/straight-server/orders_controller.rb:55:in `block (2 levels) in create'
    /var/lib/gems/2.1.0/gems/logmaster-0.1.5/lib/logmaster.rb:54:in `watch_exceptions'
    /var/lib/gems/2.1.0/gems/straight-server-0.2.3/lib/straight-server/orders_controller.rb:54:in `block in create'

Is there something I can do to fix this ?

Thanks,

Mat

**Comment by AlexanderPavlenko** [comment]
It was fixed by https://github.com/MyceliumGear/straight-server/commit/1ad54844a060b2fbab8e0fc764329606ebdea78f

**Comment by MBuffenoir** [comment]
Great ! thanks !

**Comment by MBuffenoir** [comment]
Can it be pushed in the gem repository ?

**Comment by MBuffenoir** [comment]
It would help make this https://registry.hub.docker.com/u/sbex/payment-processor/ function properly ...
Thanks.

**Comment by AlexanderPavlenko** [comment]
@snitko why 1.0.0 version is not present on rubygems?

**Comment by snitko** [comment]
Version 1.0.0 was just pushed to rubygems.
