### ISSUE TITLE
Bip 70?

### ISSUE THREAD

**Issue by nahtnam** [MyceliumGear/straight-server#4]
Hey!

Would it be possible to implement BIP 70 (merchant) + HD? I believe the multibit wallet supports this: https://multibit.org/blog/2015/04/14/multibit-hd-beta-8.html

Thoughts?

**Comment by snitko** [comment]
We'll add it to the TODO list, thanks.

**Comment by nahtnam** [comment]
Yeah, basically it lets you make payment requests, get refund addresses, etc while still being HD.
