### ISSUE TITLE
Unable to create Gateway using straight-console

### ISSUE THREAD

**Issue by MBuffenoir** [MyceliumGear/straight-server#42]
Hello,

I've been trying to store the config of my Gateway in the database as per the README and Alexander advice.

I'm getting the following error and I'm not really versed enough in Ruby to understand sequel documentation:

```
straight-console  --config-dir=/usr/src/app/straight-server-config/
/var/lib/gems/2.1.0/gems/straight-1.0.0/lib/straight/faraday_monkeypatch.rb:1: warning: already initialized constant Faraday::SSLOptions
/var/lib/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/options.rb:205: warning: previous definition of SSLOptions was here
Setting config dir to /usr/src/app/straight-server-config
irb(main):001:0> gateway = Gateway.new
NameError: uninitialized constant Gateway
	from (irb):1
	from /var/lib/gems/2.1.0/gems/straight-server-1.0.0/bin/straight-console:12:in `<top (required)>'
	from /usr/local/bin/straight-console:23:in `load'
	from /usr/local/bin/straight-console:23:in `<main>'
```
Using the 1.0 version from the gem file

Thanks for your help

**Comment by AlexanderPavlenko** [comment]
Try `StraightServer::Gateway`

**Comment by MBuffenoir** [comment]
OK This works, then I'm entering values for :

> gateway.pubkey                 = 'xpub1234'
> gateway.confirmations_required = 0
> gateway.order_class            = 'StraightServer::Order'
> gateway.callback_url           = 'http://myapp.com/payment_callback'
> gateway.save

But the save is failing with :

```irb(main):014:0> gateway.save
TypeError: no implicit conversion of nil into String
        from /var/lib/gems/2.1.0/gems/straight-server-1.0.0/lib/straight-server/gateway.rb:433:in `update'````

Reading from the code I thought this was due to not having a server_secret file in my config, but it is present with a secret in it

Am I missing something here ?

**Comment by MBuffenoir** [comment]
OK, found it, gateway.name also needs to be specified (not sure if secret is mandatory too but I've added it)

**Comment by MBuffenoir** [comment]
secret is not needed, thanks for you help, hope it serves others...

Great job on straight-server otherwise guys

**Comment by gabiruiz91** [comment]
Hi @MBuffenoir  can you help me? how do you set the secret and how do you get it? I'm stuck
