### ISSUE TITLE
NoMethodError: undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by btcontract** [MyceliumGear/straight-server#51]
When `test_mode: true` is set in config.ymg a POST to `http://localhost:9696/gateways/1/orders?amount=500000` yields an error with the following output in console:

> I, [2016-02-10T14:25:44.271991 #27288]  INFO -- : POST /gateways/1/orders
> {"amount"=>"500000"}
> I, [2016-02-10T14:25:44.272294 #27288]  INFO -- : Creating new order with attrs: {:amount=>"500000", :currency=>nil, :btc_denomination=>nil, :keychain_id=>nil, :callback_data=>nil, :data=>nil, :description=>nil}
> F, [2016-02-10T14:25:44.275719 #27288] FATAL -- : NoMethodError: undefined method `+' for nil:NilClass
> Backtrace:
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/straight-server-1.0.0/lib/straight-server/gateway.rb:165:in`get_next_last_keychain_id'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/straight-server-1.0.0/lib/straight-server/gateway.rb:142:in `create_order'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/straight-server-1.0.0/lib/straight-server/orders_controller.rb:55:in`create'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/straight-server-1.0.0/lib/straight-server/orders_controller.rb:169:in `dispatch'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/straight-server-1.0.0/lib/straight-server/orders_controller.rb:16:in`initialize'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:133:in `new'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:133:in`block in initialize_routes'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:71:in `call'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:71:in`block in process_request'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:70:in `each'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:70:in`process_request'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:43:in `block in response'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/logmaster-0.1.5/lib/logmaster.rb:54:in`watch_exceptions'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:36:in `response'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/goliath-1.0.4/lib/goliath/api.rb:163:in`call'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/faye-websocket-0.10.2/lib/faye/adapters/goliath.rb:28:in `call'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/goliath-1.0.4/lib/goliath/rack/params.rb:65:in`block in call'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/goliath-1.0.4/lib/goliath/rack/validator.rb:40:in `safely'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/goliath-1.0.4/lib/goliath/rack/params.rb:63:in`call'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/goliath-1.0.4/lib/goliath/rack/async_middleware.rb:73:in `call'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/content_length.rb:15:in`call'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:114:in `call'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:91:in`block in new'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/reloader.rb:44:in `call'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/reloader.rb:44:in`call'
>     /home/anton/.rvm/gems/ruby-2.2.1/gems/goliath-1.0.4/lib/goliath/request.rb:166:in `block in process'

It does not happen with `test_mode: false`

**Comment by lichtamberg** [comment]
Did you solve this problem? I also have it at the moment...
