### ISSUE TITLE
bitcoind support

### ISSUE THREAD

**Issue by tomtruitt** [MyceliumGear/straight-server#65]
Hi not really an issue just curious what would it take to support bitcoind instead of relying on third-party services?

**Comment by AlexanderPavlenko** [comment]
I doubt that it can be used directly. BlockchainAdapter has to implement `fetch_transactions_for(address)` method and I do not see any analogue in https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list.

InsightAdapter can be used with https://github.com/bitpay/insight-api/tree/038eb401db830ba15873ec73030c2ec65584e3ac on top of bitcoind without relying on third-party services.

**Comment by tomtruitt** [comment]
thanks you for the reply... i actually meant to ask for bitcoin core... https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs does this change things?

**Comment by tomtruitt** [comment]
hmmm InsightAdapter may be just what i'm looking for anyway thank you again.

**Comment by tomtruitt** [comment]
lol actually this is from your link 

Warning

Insight file sync does not work with bitcoind v0.10 In order to use Insigtht you must set the environment variable INSIGHT_FORCE_RPC_SYNC = 1
We are working on bitcore-node to replace Insight-api. Check bitcore-node on github.

**Comment by tomtruitt** [comment]
this looks like updated link for Insight https://github.com/bitpay/insight-api/tree/v0.3.0

**Comment by tomtruitt** [comment]
I'm sorry if this is asking for too much hand holding but guess I'm really asking what needs to be done to point straight-server to a full node vs a third-party service?

**Comment by tomtruitt** [comment]
Roughly

**Comment by AlexanderPavlenko** [comment]
InsightAdapter is not yet tested against bitcore-node with insight-api, but there's a good chance it will work without modifications.

**Comment by tomtruitt** [comment]
Thank you!
