### ISSUE TITLE
Outdated version 

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [MyceliumGear/straight-server#68]
Could you maybe release a new gem version? The last one is 10 months old and i think is has quite changed a lot in the meantime...

thanks!

**Comment by cmstest** [comment]
+1 for this! Needed urgently :)

**Comment by AlexanderPavlenko** [comment]
Hello! In case this is still an issue, feel free to submit it to https://github.com/mycelium-com/gear-engine/issues
