### ISSUE TITLE
Address Threshold Limit

### ISSUE THREAD

**Issue by firebird2490** [MyceliumGear/straight-server#81]
I'm trying to implement this project for my website but want to increase the address threshold limit. I cannot seem to find where `Config.reuse_address_orders_threshold ` is defined. How do i change the default limit?

**Comment by AlexanderPavlenko** [comment]
It's defined in the `config.yml`
https://github.com/MyceliumGear/straight-server/blob/52922b677331ceeeca0798e784857d65d460f397/templates/config.yml#L22

**Comment by firebird2490** [comment]
Thanks Alexander Pavlenko.
