### ISSUE TITLE
BTC::FormatError: Invalid Base58Check string: checksum invalid

### ISSUE THREAD

**Issue by gengkeye** [MyceliumGear/straight-server#84]
I installed the gem straight-server-kit and used the command client.orders.create(order) to create an order, but I got an error:
--------------------------------------------------------------------------------------------------------------------------
, [2017-03-16T16:39:29.542242 #10076]  INFO -- : POST /gateways/1/orders
{"amount"=>"1.0", "callback_data"=>"1", "keychain_id"=>1}
I, [2017-03-16T16:39:29.542715 #10076]  INFO -- : Creating new order with attrs: {:amount=>"1.0", :currency=>nil, :btc_denomination=>nil, :keychain_id=>1, :callback_data=>"1", :data=>nil, :description=>nil, :after_payment_redirect_to=>nil, :auto_redirect=>nil}
E, [2017-03-16T16:39:30.614847 #10076] ERROR -- : Process request error: #<BTC::FormatError: Invalid Base58Check string: checksum invalid in "tpub6Cw8K4QJa6T2SrgkNXYTfUVP9zTX8V2LKtrDxTPAL7cUiKZPWboJY1mi8QVbNFWuycsiWMUscPm2HH5x5pgckP5sutNGszFgnbRBAabzy9Q">
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/btcruby-1.1.1/lib/btcruby/base58.rb:75:in `data_from_base58check'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/btcruby-1.1.1/lib/btcruby/keychain.rb:227:in `init_with_extended_key'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/btcruby-1.1.1/lib/btcruby/keychain.rb:204:in `initialize'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/straight-67b2e1679fb8/lib/straight/gateway.rb:141:in `new'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/straight-67b2e1679fb8/lib/straight/gateway.rb:141:in `keychain'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/straight-67b2e1679fb8/lib/straight/address_providers/bip32.rb:10:in `new_address'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/straight-67b2e1679fb8/lib/straight/gateway.rb:106:in `new_order'
/home/seven/app/straight-server/lib/straight-server/gateway.rb:144:in `create_order_concurrently'
/home/seven/app/straight-server/lib/straight-server/gateway.rb:120:in `block in create_order'
/home/seven/app/straight-server/lib/straight-server/gateway.rb:119:in `synchronize'
/home/seven/app/straight-server/lib/straight-server/gateway.rb:119:in `create_order'
/home/seven/app/straight-server/lib/straight-server/orders_controller.rb:43:in `create'
/home/seven/app/straight-server/lib/straight-server/orders_controller.rb:166:in `dispatch'
/home/seven/app/straight-server/lib/straight-server/orders_controller.rb:17:in `initialize'
/home/seven/app/straight-server/lib/straight-server/initializer.rb:146:in `new'
/home/seven/app/straight-server/lib/straight-server/initializer.rb:146:in `block in initialize_routes'
/home/seven/app/straight-server/lib/straight-server/server.rb:79:in `block in process_request'
/home/seven/app/straight-server/lib/straight-server/server.rb:78:in `each'
/home/seven/app/straight-server/lib/straight-server/server.rb:78:in `process_request'
/home/seven/app/straight-server/lib/straight-server/server.rb:50:in `block in response'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/logmaster-0.2.0/lib/logmaster.rb:60:in `watch_exceptions'
/home/seven/app/straight-server/lib/straight-server/server.rb:43:in `response'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/goliath-1.0.4/lib/goliath/api.rb:163:in `call'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faye-websocket-0.10.0/lib/faye/adapters/goliath.rb:28:in `call'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/goliath-1.0.4/lib/goliath/rack/params.rb:65:in `block in call'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/goliath-1.0.4/lib/goliath/rack/validator.rb:40:in `safely'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/goliath-1.0.4/lib/goliath/rack/params.rb:63:in `call'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/goliath-1.0.4/lib/goliath/rack/async_middleware.rb:73:in `call'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:114:in `call'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:91:in `block in new'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/reloader.rb:44:in `call'
/home/seven/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/goliath-1.0.4/lib/goliath/request.rb:166:in `block in process'
--------------------------------------------------------------------------------------------------------------------------------

**Comment by AlexanderPavlenko** [comment]
Hello! In case this is still an issue, feel free to submit it to https://github.com/mycelium-com/gear-engine/issues
