### ISSUE TITLE
Problem on Mycelium Gear Online

### ISSUE THREAD

**Issue by Uter1007** [MyceliumGear/straight-server#91]
Hi,

don't know if I am right here. I am using the online service of mycelium gear. Currently we got a major issue in the form of not captured transactions. We are using a blockchain.info account with the xpub (BIP32) address. The transactions are correctly sent by the customers + even got more than 6 confirmations already, but mycelium doesn't recognize the transactions and so it will be flagged as expired. Sometimes some transactions are correctly captured but I would say ~80% of the transactions are just expired. What can we do to change that ? Should we increase the order time, does mycelium doing any scheduling jobs (so my hope is that they will be flagged correctly over time) ? Are we doing anything wrong on our side ?  

cheers,
Christoph

**Comment by Uter1007** [comment]
btw. the official Email address: gear.support@mycelium.com  doesn't work :(

**Comment by Uter1007** [comment]
+ is it possible to decrease the number of used keychain adresses for unexpired orders -> blockchain.info just using 15 addresses. Would it be ok to use only 15 addresses in total or will this interfere with mycelium ? Are there any prefered ways to handle it as best, because I am not able to assure that I am using only 20 expiration adresses. I will always ask the last keychain and will add +1 but so I will run into the problem that blockchain.info couldn't track any transaction. I am also thinking about to use one keychain id per 4hours so I won't run into to far distances. In the documentation it was written, that on the 21 expired order it will be used 20 order keychain_id -> I cant confirm that.... It still add +1 on every order creation.

**Comment by Uter1007** [comment]
sorry for all this questions - If I have 20 expired orders and I am canceling some of them will the keychain be reduced or doesn't change this behavior -> so it won't change anything?

**Comment by AlexanderPavlenko** [comment]
Hello! In case this is still an issue, feel free to submit it to https://github.com/mycelium-com/gear-engine/issues
