### ISSUE TITLE
Error: incompatible marshal file format

### ISSUE THREAD

**Issue by gabiruiz91** [MyceliumGear/straight-server#94]
Hi guys good afternoon, I'm setting up a straight-server in ubuntu 16 and the server starts ok, it generate gateways and orders on the DB correctly, but only in BTC currency, when I try to generate in USD o EUR it sends the next error:

^Croot@ubuntu-s-2vcpu-4gb-sfo2-01-BTC-process:~# straight-server -p 9696
/usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/faraday_monkeypatch.rb:1: warning: already initialized constant Faraday::SSLOptions
/usr/share/rvm/gems/ruby-2.5.1/gems/faraday-0.15.2/lib/faraday/options.rb:218: warning: previous definition of SSLOptions was here
Setting config dir to /root/.straight
I, [2018-08-09T22:48:32.226964 #17011]  INFO -- : starting Straight Server v 1.0.0

I, [2018-08-09T22:48:36.623765 #17011]  INFO -- : POST /gateways/0bed1c74cc5fa8deb1c0db270b34d54e5e2f871a2673b1e837515c9e45ea15fd/orders
{"amount"=>"100"}
I, [2018-08-09T22:48:36.625630 #17011]  INFO -- : Creating new order with attrs: {:amount=>"100", :currency=>nil, :btc_denomination=>nil, :keychain_id=>nil, :callback_data=>nil, :data=>nil, :description=>nil}
F, **[2018-08-09T22:48:36.627979 #17011] FATAL -- : Straight::GatewayModule::NoAdaptersAvailable: the list of exchange rate adapters is empty or nil**
Backtrace:
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/gateway.rb:188:in `try_adapters'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/gateway.rb:157:in `amount_from_exchange_rate'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/gateway.rb:99:in `new_order'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/gateway.rb:140:in `create_order'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/orders_controller.rb:55:in `create'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/orders_controller.rb:169:in `dispatch'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/orders_controller.rb:16:in `initialize'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:133:in `new'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:133:in `block in initialize_routes'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:71:in `block in process_request'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:70:in `each'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:70:in `process_request'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:43:in `block in response'
    /usr/share/rvm/gems/ruby-2.5.1/gems/logmaster-0.1.5/lib/logmaster.rb:54:in `watch_exceptions'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:36:in `response'
    /usr/share/rvm/gems/ruby-2.5.1/gems/goliath-1.0.6/lib/goliath/api.rb:163:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/faye-websocket-0.10.7/lib/faye/adapters/goliath.rb:28:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/goliath-1.0.6/lib/goliath/rack/params.rb:67:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/goliath-1.0.6/lib/goliath/rack/async_middleware.rb:73:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/rack-1.6.10/lib/rack/content_length.rb:15:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:114:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:91:in `block in new'
    /usr/share/rvm/gems/ruby-2.5.1/gems/rack-1.6.10/lib/rack/reloader.rb:45:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/goliath-1.0.6/lib/goliath/request.rb:166:in `block in process'
the value of exchange adapter was NULL
![image](https://user-images.githubusercontent.com/11684358/43930026-ab499992-9c0d-11e8-8c10-62e1b1da8926.png)

After that, in the DB I put in the next values
![image](https://user-images.githubusercontent.com/11684358/43930089-04524e8a-9c0e-11e8-8731-2e2613af2635.png)

and that was the next error:
^Croot@ubuntu-s-2vcpu-4gb-sfo2-01-BTC-process:~# straight-server -p 9696
/usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/faraday_monkeypatch.rb:1: warning: already initialized constant Faraday::SSLOptions
/usr/share/rvm/gems/ruby-2.5.1/gems/faraday-0.15.2/lib/faraday/options.rb:218: warning: previous definition of SSLOptions was here
Setting config dir to /root/.straight
I, [2018-08-09T22:49:13.853265 #17013]  INFO -- : starting Straight Server v 1.0.0
^Croot@ubuntu-s-2vcpu-4gb-sfo2-01-BTC-process:~# straight-server -p 9696
/usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/faraday_monkeypatch.rb:1: warning: already initialized constant Faraday::SSLOptions
/usr/share/rvm/gems/ruby-2.5.1/gems/faraday-0.15.2/lib/faraday/options.rb:218: warning: previous definition of SSLOptions was here
Setting config dir to /root/.straight
I, [2018-08-09T22:53:03.589397 #17106]  INFO -- : starting Straight Server v 1.0.0

I, [2018-08-09T22:53:07.256709 #17106]  INFO -- : POST /gateways/0bed1c74cc5fa8deb1c0db270b34d54e5e2f871a2673b1e837515c9e45ea15fd/orders
{"amount"=>"100"}
**F, [2018-08-09T22:53:07.258544 #17106] FATAL -- : TypeError: incompatible marshal file format (can't be read)
        format version 4.8 required; 6.43 given**
Backtrace:
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/plugins/serialization.rb:100:in `load'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/plugins/serialization.rb:100:in `block in <module:Serialization>'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/plugins/serialization.rb:203:in `deserialize_value'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/plugins/serialization.rb:154:in `block (3 levels) in define_serialized_attribute_accessor'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/gateway.rb:61:in `initialize_exchange_rate_adapters'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/gateway.rb:398:in `after_initialize'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/plugins/after_initialize.rb:20:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/dataset/actions.rb:935:in `block in with_sql_each'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/adapters/sqlite.rb:335:in `block (2 levels) in fetch_rows'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sqlite3-1.3.13/lib/sqlite3/resultset.rb:138:in `each'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/adapters/sqlite.rb:326:in `block in fetch_rows'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:267:in `query'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/adapters/sqlite.rb:187:in `block (2 levels) in _execute'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/adapters/sqlite.rb:187:in `block in _execute'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/database/connecting.rb:270:in `synchronize'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/adapters/sqlite.rb:180:in `_execute'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/adapters/sqlite.rb:126:in `execute'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/dataset/actions.rb:1083:in `execute'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/adapters/sqlite.rb:320:in `fetch_rows'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/dataset/actions.rb:935:in `with_sql_each'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/dataset/actions.rb:945:in `with_sql_first'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/dataset/actions.rb:701:in `single_record!'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/dataset/actions.rb:689:in `single_record'
    /usr/share/rvm/gems/ruby-2.5.1/gems/sequel-5.11.0/lib/sequel/dataset/actions.rb:207:in `first'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/gateway.rb:367:in `find_by_hashed_id'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/orders_controller.rb:153:in `dispatch'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/orders_controller.rb:16:in `initialize'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:133:in `new'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:133:in `block in initialize_routes'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:71:in `block in process_request'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:70:in `each'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:70:in `process_request'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:43:in `block in response'
    /usr/share/rvm/gems/ruby-2.5.1/gems/logmaster-0.1.5/lib/logmaster.rb:54:in `watch_exceptions'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:36:in `response'
    /usr/share/rvm/gems/ruby-2.5.1/gems/goliath-1.0.6/lib/goliath/api.rb:163:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/faye-websocket-0.10.7/lib/faye/adapters/goliath.rb:28:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/goliath-1.0.6/lib/goliath/rack/params.rb:67:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/goliath-1.0.6/lib/goliath/rack/async_middleware.rb:73:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/rack-1.6.10/lib/rack/content_length.rb:15:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:114:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:91:in `block in new'
    /usr/share/rvm/gems/ruby-2.5.1/gems/rack-1.6.10/lib/rack/reloader.rb:45:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/goliath-1.0.6/lib/goliath/request.rb:166:in `block in process'

Any ideas what is that I'm doing wrong?

**Comment by gabiruiz91** [comment]
y Solved this inserting the adapters like this:

 DB = Sequel.sqlite('/root/.straight/straight.db')
 gateguay = DB[:gateways]
 gateguay.update(exchange_rate_adapter_names: Marshal.dump(["Bitpay"]))

**Comment by AlexanderPavlenko** [comment]
Hello! In case this is still an issue, feel free to submit it to https://github.com/mycelium-com/gear-engine/issues
