### ISSUE TITLE
FATAL -- : Satoshi::TooManyDigitsAfterDecimalPoint:

### ISSUE THREAD

**Issue by gabiruiz91** [MyceliumGear/straight-server#95]
hi guys, I just want to make an order with USD currency and I am getting the next error:
 **FATAL -- : Satoshi::TooManyDigitsAfterDecimalPoint: Too many digits (20) after decimal point used for btc value, while 8 allowed**

root@ubuntu-s-2vcpu-4gb-sfo2-01-BTC-process:~# straight-server -p 9696
/usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/faraday_monkeypatch.rb:1: warning: already initialized constant Faraday::SSLOptions
/usr/share/rvm/gems/ruby-2.5.1/gems/faraday-0.15.2/lib/faraday/options.rb:218: warning: previous definition of SSLOptions was here
Setting config dir to /root/.straight
I, [2018-08-10T22:57:12.627270 #1658]  INFO -- : starting Straight Server v 1.0.0

I, [2018-08-10T23:01:22.396766 #1658]  INFO -- : POST /gateways/0bed1c74cc5fa8deb1c0db270b34d54e5e2f871a2673b1e837515c9e45ea15fd/orders
{"amount"=>"1", "currency"=>"USD"}
I, [2018-08-10T23:01:22.398397 #1658]  INFO -- : Creating new order with attrs: {:amount=>"1", :currency=>"USD", :btc_denomination=>nil, :keychain_id=>nil, :callback_data=>nil, :data=>nil, :description=>nil}
F, [2018-08-10T23:01:22.426246 #1658] FATAL -- : Satoshi::TooManyDigitsAfterDecimalPoint: Too many digits (20) after decimal point used for btc value, while 8 allowed
Backtrace:
    /usr/share/rvm/gems/ruby-2.5.1/gems/satoshi-unit-0.2.2/lib/satoshi.rb:147:in `convert_to_satoshi'
    /usr/share/rvm/gems/ruby-2.5.1/gems/satoshi-unit-0.2.2/lib/satoshi.rb:24:in `initialize'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/exchange_rate_adapter.rb:17:in `new'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/exchange_rate_adapter.rb:17:in `convert_from_currency'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/gateway.rb:158:in `block in amount_from_exchange_rate'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/gateway.rb:193:in `block in try_adapters'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/gateway.rb:191:in `each'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/gateway.rb:191:in `try_adapters'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/gateway.rb:157:in `amount_from_exchange_rate'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-1.0.0/lib/straight/gateway.rb:99:in `new_order'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/gateway.rb:140:in `create_order'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/orders_controller.rb:55:in `create'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/orders_controller.rb:169:in `dispatch'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/orders_controller.rb:16:in `initialize'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:133:in `new'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:133:in `block in initialize_routes'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:71:in `block in process_request'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:70:in `each'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:70:in `process_request'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:43:in `block in response'
    /usr/share/rvm/gems/ruby-2.5.1/gems/logmaster-0.1.5/lib/logmaster.rb:54:in `watch_exceptions'
    /usr/share/rvm/gems/ruby-2.5.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:36:in `response'
    /usr/share/rvm/gems/ruby-2.5.1/gems/goliath-1.0.6/lib/goliath/api.rb:163:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/faye-websocket-0.10.7/lib/faye/adapters/goliath.rb:28:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/goliath-1.0.6/lib/goliath/rack/params.rb:67:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/goliath-1.0.6/lib/goliath/rack/async_middleware.rb:73:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/rack-1.6.10/lib/rack/content_length.rb:15:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:114:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:91:in `block in new'
    /usr/share/rvm/gems/ruby-2.5.1/gems/rack-1.6.10/lib/rack/reloader.rb:45:in `call'
    /usr/share/rvm/gems/ruby-2.5.1/gems/goliath-1.0.6/lib/goliath/request.rb:166:in `block in process'

**Comment by mikeh21** [comment]
satoshi-unit-0.2.2 causes this error. downgrade to satoshi-unit-0.1.8 and its working

**Comment by AlexanderPavlenko** [comment]
Hello! In case this is still an issue, feel free to submit it to https://github.com/mycelium-com/gear-engine/issues
