### ISSUE TITLE
Problem with X-signature

### ISSUE THREAD

**Issue by gabiruiz91** [MyceliumGear/straight-server#96]
Hí guys when I created the gateway using straight-console I put this:

gateway.pubkey = *******
gateway.confirmations_required = 0
gateway.default_currency = 'USD'
gateway.order_class = 'StraightServer::Order'
gateway.callback_url = ******
gateway.secret = 'TheSecretOfSecrets'
gateway.name = *******
gateway.save

and in The database is stored a crypted version of  'TheSecretOfSecrets' that look like this: '3c95121568KkasKSDksubVHkqKozNRFHy1Fw=='

Now, my doubt is: What 'secret' I have to use to make the x-signature? the raw version or the crypted?

**Comment by AlexanderPavlenko** [comment]
Hello! In case this is still an issue, feel free to submit it to https://github.com/mycelium-com/gear-engine/issues
